name: Deploy Repository to AWS
description: Custom Action To Deploy Code to AWS (Lambda)
inputs:
  aws-access-key-id:
    description: "Access Key ID for AWS"
    required: true
  aws-secret-access-key:
    description: "Secret Access key for AWS"
    required: true
  aws-region:
    description: "AWS Region for deployment"
    required: true
    default: "us-east-1"
runs:
  using: "composite"
  steps:
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}
    - run: npm run release
      shell: bash
